config/routes.rb
COMECONELIA::Application.routes.draw do
  resources :algos

  devise_for :usuarios

  root 'usuarios#index'

  

end

app/models/algo.rb
class Algo < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  #attr_accessor :login

  validates :username, :uniqueness => { :case_sensitive => false }, :unless => Proc.new { |usuario| usuario.username.blank? }
  validates_presence_of :username
end

app/controllers/algos_controller.rb
class AlgosController < ApplicationController
  before_action :set_algo, only: [:show, :edit, :update, :destroy]

  # GET /algos
  # GET /algos.json
  def index
    @algos = Algo.all
  end

  # GET /algos/1
  # GET /algos/1.json
  def show
  end

  # GET /algos/new
  def new
    @algo = Algo.new
  end

  # GET /algos/1/edit
  def edit
  end

  # POST /algos
  # POST /algos.json
  def create
    @algo = Algo.new(algo_params)

    respond_to do |format|
      if @algo.save
        format.html { redirect_to @algo, notice: 'Algo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @algo }
      else
        format.html { render action: 'new' }
        format.json { render json: @algo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /algos/1
  # PATCH/PUT /algos/1.json
  def update
    respond_to do |format|
      if @algo.update(algo_params)
        format.html { redirect_to @algo, notice: 'Algo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @algo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algos/1
  # DELETE /algos/1.json
  def destroy
    @algo.destroy
    respond_to do |format|
      format.html { redirect_to algos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_algo
      @algo = Algo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def algo_params
      params.require(:algo).permit(:nombre, :fecha)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_usuario!

  before_filter :usuario_params_registration, if: :devise_controller?

	def usuario_params_registration
	  devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation)}
	end
	
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
end

app/helpers/algos_helper.rb
module AlgosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :usuario
  end

  def resource
    @resource ||= Usuario.new(usuario_params)
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:usuario]
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/algos/_form.html.erb
<%= form_for(@algo) do |f| %>
  <% if @algo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@algo.errors.count, "error") %> prohibited this algo from being saved:</h2>

      <ul>
      <% @algo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.check_box :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/algos/edit.html.erb
<h1>Editing algo</h1>

<%= render 'form' %>

<%= link_to 'Show', @algo %> |
<%= link_to 'Back', algos_path %>

app/views/algos/index.html.erb
<h1>Listing algos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @algos.each do |algo| %>
      <tr>
        <td><%= algo.nombre %></td>
        <td><%= algo.fecha %></td>
        <td><%= link_to 'Show', algo %></td>
        <td><%= link_to 'Edit', edit_algo_path(algo) %></td>
        <td><%= link_to 'Destroy', algo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Algo', new_algo_path %>

app/views/algos/new.html.erb
<h1>New algo</h1>

<%= render 'form' %>

<%= link_to 'Back', algos_path %>

app/views/algos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @algo.nombre %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @algo.fecha %>
</p>

<%= link_to 'Edit', edit_algo_path(@algo) %> |
<%= link_to 'Back', algos_path %>

app/views/layouts/application.html.erb
<!--!DOCTYPE html>
<html>
<head>
  <title>COMECONELIA</title>
  <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%#= csrf_meta_tags %>
</head>
<body>

<%#= l Date.today + 4.months, :format => :long %> <br>
<%#= date_select("fecha", "prueba", options = {}, html_options = {}) %> <br>

<%#= yield %>

</body>
</html-->

<!DOCTYPE HTML>
<!--
	Striped 2.0 by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Come con Elia</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<%= csrf_meta_tags %>
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700|Open+Sans+Condensed:300,700" rel="stylesheet" />
		<!--script src="js/config.js"></script>
		<script src="js/skel.min.js"></script>
		<script src="js/skel-panels.min.js"></script-->
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "jquery.js", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "config.js", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "skel.min.js", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "skel-panels.min.js", "data-turbolinks-track" => true %>
	  
	  <%= stylesheet_link_tag    "skel-noscript.css" %>
	  <%= stylesheet_link_tag    "style.css" %>
		<%= stylesheet_link_tag    "style-desktop.css" %>
		<%= stylesheet_link_tag    "style-wide.css" %>
		
		<%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

		<noscript>
			<!-- <link rel="stylesheet" href="css/skel-noscript.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-desktop.css" />
			<link rel="stylesheet" href="css/style-wide.css" /> -->
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
		<!--[if lte IE 7]><link rel="stylesheet" href="css/ie7.css" /><![endif]-->
	</head>
	<!--
		Note: Set the body element's class to "left-sidebar" to position the sidebar on the left.
		Set it to "right-sidebar" to, you guessed it, position it on the right.
	-->
	<body class="right-sidebar">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Content -->
					<div id="content">
						<div id="content-inner">
							
							<% if notice %>
							  <p class="alert alert-notice"><%= notice %></p>
							<% end %>
							<% if alert %>
							  <p class="alert alert-error"><%= alert %></p>
							<% end %>
							<%= yield %>

						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
					
						<!-- Logo -->
							<div id="logo">
								<h1>COME CON ELIA</h1>
							</div>
					
						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li class="current_page_item"><a href="#">Latest Post</a></li>
									<li><a href="#">Archives</a></li>
									<li><a href="#">About Me</a></li>
									<li><a href="#">Contact Me</a></li>
								</ul>
							</nav>

					</div>

			</div>

	</body>
</html>

app/views/usuarios/index.html.erb
<%= render "devise/shared/links" %>
<%= current_usuario.email %>